FROM rust:1.42-slim-buster

RUN set -ex; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
    gosu \
    openssl \
    libpq5 \
    libpq-dev \
  ; \
  \
  cargo install diesel_cli --no-default-features --features postgres

# create user for running this application
RUN set -ex; \
  groupadd --gid 1000 rust && \
  useradd --uid 1000 --gid rust --shell /bin/bash --create-home rust

COPY docker-entrypoint.sh /usr/local/docker-entrypoint.sh
EXPOSE 8000

COPY ./ /app
WORKDIR /app

CMD ["gosu", "rust", "cargo", "run"]
