FROM rust:1.42-slim-buster

RUN set -ex; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
    openssl \
    libpq5 \
    libpq-dev \
  ; \
  \
  cargo install diesel_cli --no-default-features --features postgres

COPY docker-entrypoint.sh /usr/local/docker-entrypoint.sh
EXPOSE 8000

COPY ./ /app
WORKDIR /app

CMD ["cargo", "run"]
